### ISSUE TITLE
very clean solution (codes) with bad folder structure (I think)

### ISSUE THREAD

**Issue by elyasesna** [babaktaremi/Clean-Architecture-Template#1]
very good and clean codes, you followed all principles and design patterns, but it has many class libraries (and folders) which makes the whole solution difficult to understand. It would be great if you could make a cleaner structure.

**Comment by babaktaremi** [comment]
> very good and clean codes, you followed all principles and design patterns, but it has many class libraries (and folders) which makes the whole solution difficult to understand. It would be great if you could make a cleaner structure.

one of the main purposes of clean architecture is the encapsulation and isolation of different levels. so in this solution I tried to follow this pattern. although the layering of an solution is rather subjective

**Comment by elyasesna** [comment]
But encapsulation should not come to complicated solution

**Comment by MehdiZohrevnd** [comment]
In the Utils class library EnumExcentions has misspellings . it's just a file name missing , but in my opinion it's better to be corrected .
Thanks for sharing
