### ISSUE TITLE
Example of service

### ISSUE THREAD

**Issue by ShahramNo** [babaktaremi/Clean-Architecture-Template#2]
is possible that how can use service in this repo?

**Comment by babaktaremi** [comment]
There is no such a thing as "Service"
You define contracts ( Interfaces ) In **Application Layer** and implement those contracts in **Infrastructure** Layer. and you just call those contracts in application layer.

**Comment by ShahramNo** [comment]
Thank you for your explanation,
May i ask you implement contract of (Order) 
One example is enough.

**Comment by babaktaremi** [comment]
The Example is added to the latest commit. Check the master branch
