### ISSUE TITLE
How Use Dynamic permission

### ISSUE THREAD

**Issue by ShahramNo** [babaktaremi/Clean-Architecture-Template#6]
hi, how used dynamic permission in this repo.?
please handle with a example.
 my second question is how get payload from jwt in client?
i use blazor wasm an my code is:

private IEnumerable<Claim> ParseTokenClaims(string access_token)
    {
      
        return Jose.JWT.Payload<Dictionary<string, object>>(access_token)
            .Select(keyValue => new Claim(keyValue.Key, keyValue.Value.ToString() ?? string.Empty))
            .ToArray();
    }

but dose not work . 
tanx a lot

**Comment by babaktaremi** [comment]
I will develop an example for it in the new branch. keep checking for further updates...

**Comment by babaktaremi** [comment]
Token is encrypted and cannot be parsed like that (that's why it's called JWE. Use User.Identity.FindFirstValue(string claimName) instead

**Comment by ShahramNo** [comment]
how i can decrypt this jwe in blazor?  
is it possible ?

**Comment by babaktaremi** [comment]
> how i can decrypt this jwe in blazor?  
> 
> is it possible ?
> 
> 

Nope and I would not recommend that you decrypt a JWT token in client application

just create an action ( GetUserInfo for example) and decorate it with 
```[Authorize]``` attribute. and use the ```User``` property in the action. there is also an extension for this usage
for example for getting user email you can use ```User.Identity.FindFristValue(ClaimTypes.Email)```

**Comment by babaktaremi** [comment]
For adding more claims to the access token , modify the configuration in the file below 
_[](https://github.com/babaktaremi/Clean-Architecture-Template/blob/master/CleanArc.Infrastructure.Identity/Identity/AppUserClaimsPrincipleFactory.cs)_

**Comment by babaktaremi** [comment]
Example Added
There are a lot of changes in new update
so for dynamic permission example look at this files:

[RoleManagerController](https://github.com/babaktaremi/Clean-Architecture-Template/blob/master/CleanArc.Web.Api/Controllers/V1/Admin/RoleManagerController.cs)
[RoleManagerService](https://github.com/babaktaremi/Clean-Architecture-Template/blob/master/CleanArc.Infrastructure.Identity/Identity/PermissionManager/RoleManagerService.cs)
[Related Role Command and query handlers](https://github.com/babaktaremi/Clean-Architecture-Template/tree/master/CleanArc.Application/Features/Role)

REMEMBER: each controller that is decorated with `[Authorize(ConstantPolicies.DynamicPermission)]` attribute will be considered an auth controller that needs special permission or admin role to be accessed. [Example](https://github.com/babaktaremi/Clean-Architecture-Template/blob/master/CleanArc.Web.Api/Controllers/V1/Admin/OrderManagementController.cs)
